<?php
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => '/collection/' . $this->collection->getId() . '/items/create',
    'enctype' => 'multipart/form-data',
));
?>
<section class="main-container">
    <div class="container">
        <div class="row">

            <?php echo $this->partial('partial/sidebar/admin-sidebar'); ?>

            <div class="main col-md-9 col-md-offset-1">
                <h2 class="page-title">Add Collection Item</h2>
                <div class="separator-2"></div>


                <?php echo $this->form()->openTag($form) ?>
                <div class="form-group has-feedback">
                    <label for="title"><b>Title</b></label>
                    <?php
                    echo $this->formInput($form->get('title')) . $this->formElementErrors($form->get('title'));
                    ?>
                    <i class="fa fa-pencil form-control-feedback"></i>
                </div>
                <div class="form-group has-feedback">
                    <label for="date"><b>Date</b></label>
                    <?php
                    echo $this->formDate($form->get('date')) . $this->formElementErrors($form->get('date'));
                    ?>
                    <i class="fa fa-calendar form-control-feedback"></i>
                </div>
                <div class="form-group has-feedback">
                    <label for="title"><b>External Url</b></label>
                    <?php
                    echo $this->formInput($form->get('externalUrl')) . $this->formElementErrors($form->get('externalUrl'));
                    ?>
                    <i class="fa fa-pencil form-control-feedback"></i>
                </div>
                <div class="form-group radio" style="margin-bottom:12px">
                    <div><b>Type</b></div>
                    <?php
                    echo $this->formRadio($form->get('type')) . $this->formElementErrors($form->get('type'));
                    ?>
                </div>
                <div class="form-group has-feedback">
                    <label for="file"><b>Small Description</b></label>
                    <?php
                    echo $this->formTextarea($form->get('smallDescription')) . $this->formElementErrors($form->get('smallDescription'));
                    ?>
                    <i class="fa fa-pencil form-control-feedback"></i>
                </div>
                <div class="form-group has-feedback">
                    <label for="file"><b>Details</b></label>
                    <?php
                    echo $this->formTextarea($form->get('description')) . $this->formElementErrors($form->get('description'));
                    ?>
                    <i class="fa fa-pencil form-control-feedback"></i>
                </div>
                <div class="form-group">
                    <p class="help-block"><b>Please select appropriate images for your item</b></p>
                    <label for="file">(Mandatory)</label>
                    <?php
                    echo $this->formFile($form->get('file')) . $this->formElementErrors($form->get('file'));
                    ?>
                </div>

                <div class="form-group">
                    <label for="file">(Optional)</label>
                    <?php
                    echo $this->formFile($form->get('file2')) . $this->formElementErrors($form->get('file'));
                    ?>
                </div>

                <div class="form-group">
                    <label for="file">(Optional)</label>
                    <?php
                    echo $this->formFile($form->get('file3')) . $this->formElementErrors($form->get('file'));
                    ?>
                </div>

                <div class="form-group">
                    <label for="file">(Optional)</label>
                    <?php
                    echo $this->formFile($form->get('file4')) . $this->formElementErrors($form->get('file'));
                    ?>
                </div>


                <?php if ($this->collection->getType() === \AlphaPage\Entity\PageCollection::NESTED_TYPE_COLLECTION): ?>
                    <hr style="margin-top: 50px;"/>
                    <div style="text-align: center;">
                        <h4>Nest Collection Items Configuration</h4>
                    </div>    
                    <div class="form-group">
                        <label style="font-weight: 400;">Parent Item</label>
                        <?php echo $this->formSelect($form->get('parentItem')->setAttributes(array('class' => 'form-control'))) . $this->formElementErrors($form->get('parentItem')); ?>
                    </div>

                    <div class="form-group has-feedback">
                        <label for="routeLabel"><b>Route Label</b></label>
                        <?php
                        echo $this->formInput($form->get('routeLabel')) . $this->formElementErrors($form->get('routeLabel'));
                        ?>
                        <i class="fa fa-pencil form-control-feedback"></i>
                    </div>

                    <div class="form-group has-feedback">
                        <label for="routeLabel"><b>Redirect (If Applicable)</b></label>
                        <?php
                        echo $this->formInput($form->get('redirect')) . $this->formElementErrors($form->get('redirect'));
                        ?>
                        <i class="fa fa-pencil form-control-feedback"></i>
                    </div>
                <?php endif ?>

                <input value="Preview" class="btn btn-group btn-default"  type="submit" onclick="formPreview(this.form)">
                <input value="Add Item" class="btn btn-group btn-default"  type="submit" onclick="formSubmit(this.form)">                        
                <?php echo $this->form()->closeTag() ?>
            </div>
        </div>
    </div>
</section>

<script>
    function formPreview(form) {
        console.log('HERE');
        form.target = '_blank';
        form.action = '<?php echo '/collection/' . $this->collection->getId() . '/items/preview' ?>';
        //form.trigger('click');
    }

    function formSubmit(form) {
        form.target = '_self';
        form.action = '<?php echo '/collection/' . $this->collection->getId() . '/items/create' ?>';
        //form.trigger('click');
    }
</script> 



