<?php
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => '/collection/create',
));
?>

<section class="main-container">
    <div class="container">
        <div class="row">

            <?php echo $this->partial('partial/sidebar/admin-sidebar'); ?>

            <div class="main col-md-9 col-md-offset-1">
                <h2 class="page-title">Add New Collection</h2>
                <div class="separator-2"></div>
                <?php echo $this->form()->openTag($form); ?>

                <div class="form-group">
                    <label style="font-weight: 400;">Name</label>
                    <?php echo $this->formInput($form->get('name')->setAttributes(array('class' => 'form-control'))) . $this->formElementErrors($form->get('name')); ?>
                </div>

                <div class="form-group">
                    <label style="font-weight: 400;">Description</label>
                    <?php echo $this->formInput($form->get('description')->setAttributes(array('class' => 'form-control'))) . $this->formElementErrors($form->get('description')); ?>
                </div>

                <div class="form-group radio" style="margin-bottom:12px">
                    <div><b>Type</b></div>
                    <?php
                    echo $this->formRadio($form->get('type')) . $this->formElementErrors($form->get('type'));
                    ?>
                </div>

                <button class="btn btn-group btn-default btn-animated" type="submit">Create Collection<i class="fa fa-plus"></i></button>
                    <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</section>


