<?php
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
));
?>
<section class="main-container">
    <div class="container">
        <div class="row">

            <?php echo $this->partial('partial/sidebar/admin-sidebar'); ?>

            <div class="main col-md-9 col-md-offset-1">
                <?php echo $this->partial('partial/flashmessanger/flash-messanger.phtml'); ?>
                <h2 class="page-title"><?php echo $this->page->getName() ?></h2>
                <p><i class = "fa fa-info-circle"></i> Submitted changes go online immediately</p>
                <p><i class = "fa fa-clock-o"></i> Last Modified On: <b><?php echo $this->page->getLastModified()->format('Y-m-d H:i:s'); ?></b></p>
                <p><i class = "fa fa-user"></i> Last Edited By: <b><?php echo ($this->page->getEditor() !== null) ? $this->page->getEditor()->getEmail() : '' ?></b></p>
                <div class = "separator-2"></div><br>

                <?php echo $this->form()->openTag($form); ?>
                <div class="form-group has-feedback">
                    <label style="font-weight: 400;">Page HTML</label>
                    <?php echo $this->formTextarea($form->get('content')) . $this->formElementErrors($form->get('content')); ?>
                </div>
                <button class="btn btn-group btn-default btn-animated" type="submit" onclick="formPreview(this.form)">Preview<i class="fa fa-eye"></i></button>
                <button class="btn btn-group btn-default btn-animated" type="submit" onclick="formSubmit(this.form)">Submit<i class="fa fa-check-circle"></i></button>                        
                    <?php echo $this->form()->closeTag(); ?>

            </div>
        </div>
    </div>
</section>

<script language="JavaScript">
    function formPreview(form) {
        form.target = '_blank';
        form.action = '/page/preview/<?php echo $this->page->getName() ?>';
    }

    function formSubmit(form) {
        form.target = '_self';
        form.action = '/page/edit/<?php echo $this->page->getName() ?>';
    }
</script> 

